install.packages("ncdf")
install.packages("zoo")
install.packages("chron")
install.packages("clim.pact")
install.packages("lattice")
install.packages("Rwave")
install.packages("RSEIS")
install.packages("fUtilities")
#Manuell "sowas" installieren (nicht in CRAN) 
